### PR TITLE
Readme contribution

### PR DESCRIPTION
**Pull request by yadavsairaj**
1. Folder added
2. Added screenshots
3. Edited the README.md file and change the markdown links to point to the new Screenshot locations

### CODE REVIEW

**Comment by yadavsairaj** [comment]
Hey @johnwalicki **Everything is done**. I apologize for taking it forever, this is the very first time I'm contributing to open source.
Please check.
While merging please add the **hacktoberfest-accepted** label.
Thankyou. :)

**Review by johnwalicki — APPROVED** [review]
LGTM

**Comment by johnwalicki** [comment]
@yadavsairaj - Glad you worked through the issues.  Looks great. Congratulations on your first PR.  Thanks for contributing to Open Horizon.

**Comment by yadavsairaj** [comment]
Thankyou so much for giving me this opportunity.

**Pull request merged**
