### PR TITLE
Moved screenshot to another screenshot directory

### PR DESCRIPTION
**Pull request by yadavsairaj**
Moved README screenshot images to a screenshots/ directory

### CODE REVIEW

**Comment by yadavsairaj** [comment]
Hey @johnwalicki the task is done .  After succesful merging please add the hacktoberfest-accepted label. 
Thankyou.

**Comment by johnwalicki** [comment]
@yadavsairaj  Thanks - can you also need to edit the README.md file and change the markdown links to point to the new Screenshot locations?

**Comment by joewxboy** [comment]
@yadavsairaj Also, to get Hacktoberfest credit, you probably don't want it merged until October 1st. :)

**Comment by yadavsairaj** [comment]
> @yadavsairaj Thanks - can you also need to edit the README.md file and change the markdown links to point to the new Screenshot locations?

Ya sure! will do that.

**Comment by yadavsairaj** [comment]
The directory is not visible. So when i add markdown list it is not updating and it goes to a 404 page. 
TRYING AGAIN.

**Pull request closed without merging**
