### PR TITLE
Issue-11: Added current dir param to build target

### PR DESCRIPTION
**Pull request by joewxboy**
Added `.` for current directory at end of `docker build` lines.  Tested locally on MacBook.

### CODE REVIEW

**Review by johnwalicki — COMMENTED** [review]
```
-f ./Dockerfile .
```
The extra dot seems unnecessary.  The `./Dockerfile` says use the Dockerfile in the current directory.  This works correctly on Linux.  Is there a different current directory on Mac or your system?

**Comment by johnwalicki** [comment]
What does ` make -n build` report?

**Comment by joewxboy** [comment]
> What does ` make -n build` report?

Without the fix:

```
make -n build
docker build --platform linux/arm64 -t docker.io/walicki/service-node-red-hello-world_arm64:1.1.0 -f ./Dockerfile
docker build --platform linux/amd64 -t docker.io/walicki/service-node-red-hello-world_amd64:1.1.0 -f ./Dockerfile
docker image prune --filter label=stage=builder --force
```

and

```
make build
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
make: *** [build] Error 1
```

By adding the path argument of `.` to the end of the two `docker build` lines, it works.

**Comment by joewxboy** [comment]
With the fix, and with my `DOCKER_HUB_ID` var set, it becomes:

```
make -n build
docker build --platform linux/arm64 -t docker.io/joewxboy/service-node-red-hello-world_arm64:1.1.0 -f ./Dockerfile .
docker build --platform linux/amd64 -t docker.io/joewxboy/service-node-red-hello-world_amd64:1.1.0 -f ./Dockerfile .
docker image prune --filter label=stage=builder --force
```

**Comment by joewxboy** [comment]
@johnwalicki Any objections or other feedback?

**Comment by johnwalicki** [comment]
Yes, its fine.  The final `.` defines the build context directory.  I'll approve the PR.

**Review by johnwalicki — APPROVED** [review]

**Pull request merged**
